language: node_js

node_js:
- lts/dubnium

before_install:
- npm install -g serverless
- pip install awscli
- mkdir build
- mkdir .serverless
- aws s3 sync s3://crypto-seo/deployment/build ./build
- aws s3 sync s3://crypto-seo/deployment/.serverless ./.serverless

install:
- npm install

script:
- npm run build-contract
- npm run test

addons:
  ssh_known_hosts: jaspa.codes

before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env -d  
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script:
  - serverless deploy
  - truffle migrate --network kovaninfura
  - npm run build-frontend
  - rsync -r --delete-after $TRAVIS_BUILD_DIR/dist travis-ci@jaspa.codes:/var/www/crypto-seo
  on:
    branch: full-deployment

after_deploy:
- aws s3 sync ./build s3://crypto-seo/deployment/build
- aws s3 sync ./.serverless s3://crypto-seo/deployment/.serverless