language: node_js

node_js:
- lts/dubnium

before_install:
- npm install -g serverless
- pip install awscli
- mkdir -p $TRAVIS_BUILD_DIR/build
- mkdir -p $TRAVIS_BUILD_DIR/googleSearchAdapter/.serverless
- aws s3 sync s3://crypto-seo/deployment/build $TRAVIS_BUILD_DIR/build
- aws s3 sync s3://crypto-seo/deployment/.serverless $TRAVIS_BUILD_DIR/googleSearchAdapter/.serverless

install:
- npm install

script:
- npm run test

addons:
  ssh_known_hosts: jaspa.codes

before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env -d  
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

after_deploy:
- aws s3 sync $TRAVIS_BUILD_DIR/build s3://crypto-seo/deployment/build
- aws s3 sync $TRAVIS_BUILD_DIR/googleSearchAdapter/.serverless s3://crypto-seo/deployment/.serverless