language: node_js

node_js:
- lts/dubnium

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- rsync -r --delete-after ./deploy_rsa travis-ci@jaspa.codes:/home/travis-ci/deploy_rsa